version: "3.8"

services:
  web:
    build: .
    command: python TestAtaliware/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    driver: azure_file
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=testesenha
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: